server:
  port: 8005
spring:
  application:
    name: nacos-provider-news
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    druid:
      username: root
      password: My-Linux-Mysql123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://175.24.57.96:3306/aigov?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false